### ISSUE TITLE
just-task config.ts should use a dynamic import() to load the config

### ISSUE THREAD

**Issue by dzearing** [microsoft/just#572]
Right now, just-scripts only works with commonjs configs. Given how the ecosystem is moving to esm, this will become a point of frustration.

If you have a package with `type: "module"` set right now, you'd expect `just.config.js` to be an ESM.

`just-task` will throw:

```
yarn run v1.22.17
warning package.json: No license field
$ just-scripts build
[5:06:17 PM] x Invalid configuration file: D:\git\cloudpack2\packages\path-utilities\just.config.js
[5:06:17 PM] x Error: Error [ERR_REQUIRE_ESM]: require() of ES Module D:\git\cloudpack2\packages\path-utilities\just.config.js from D:\git\cloudpack2\node_modules\just-task\lib\config.js not supported.
Instead change the require of just.config.js in D:\git\cloudpack2\node_modules\just-task\lib\config.js to a dynamic import() which is available in all CommonJS modules.
    at Object.readConfig (D:\git\cloudpack2\node_modules\just-task\lib\config.js:30:34)
    at Object.<anonymous> (D:\git\cloudpack2\node_modules\just-task\lib\cli.js:37:31)
    at Object.<anonymous> (D:\git\cloudpack2\node_modules\just-scripts\lib\cli.js:3:1)
    at Object.<anonymous> (D:\git\cloudpack2\node_modules\just-scripts\bin\just-scripts.js:2:1)
```
 
I think the require statement can change to an async import, but that will also require some shuffling in the CLI to await on results (or Promise chain.) Plus I'm not sure how this will affect importing commonjs results - that will still need testing.

**Comment by dzearing** [comment]
This is not an issue if you use TS with a commonjs module output, but I've been trying to remove cjs output in new code.

**Comment by kaiyoma** [comment]
Any word here? I'm also running into this, and would like to use Just with ESM pretty soon. We have a big monorepo that uses Just everywhere, and we'll eventually need to convert to ESM.

**Comment by Hotell** [comment]
we are also running into this ATM 

I managed to make it work with these simple tweaks, it might be more complicated than that ... would be great to ship this.


<img width="1864" alt="image" src="https://github.com/microsoft/just/assets/1223799/4d5fed50-79cf-4708-8c6a-d968147e46ac">


https://github.com/microsoft/fluentui/pull/30582/files#r1499133479

**Comment by spookyuser** [comment]
This was such a confusing error, i couldn't figure out if this was coming from vite/just/tsconfig

**Comment by spookyuser** [comment]
> we are also running into this ATM
> 
> I managed to make it work with these simple tweaks, it might be more complicated than that ... would be great to ship this.
> 
> <img alt="image" width="1864" src="https://private-user-images.githubusercontent.com/1223799/306994667-4d5fed50-79cf-4708-8c6a-d968147e46ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NzU1NzYsIm5iZiI6MTcxNDY3NTI3NiwicGF0aCI6Ii8xMjIzNzk5LzMwNjk5NDY2Ny00ZDVmZWQ1MC03OWNmLTQ3MDgtOGM2YS1kOTY4MTQ3ZTQ2YWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMTg0MTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWMxYWMxZTQxY2NjOTQ2MGI1MzlkMTViNTk3OGViYTZmNzZhMDkxNDMwZTYwNjcyY2Q0YjJhMjc0ZTQxM2QzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XUt_h3EpoFmjuSzsPkSmTQAVClCHTMUxn3OqXV4LCZ0">
> [microsoft/fluentui#30582 (files)](https://github.com/microsoft/fluentui/pull/30582/files#r1499133479)

Thank you so much that worked, here is a pnpm patch file if anyone wants to add this to their repo fast https://gist.github.com/spookyuser/c295d14654004d2ca7b735dce4e012e9

**Comment by ecraig12345** [comment]
Support for `just.config.cjs` and `just.config.cts` was added in #756, published in `just-task` `1.11.0` and `just-scripts` `2.3.3`--thanks @NotWoods! For `.cts` you'll need `ts-node` version 10.
