### ISSUE TITLE
Rush with pnpm throws error in webpackTask

### ISSUE THREAD

**Issue by fuocor** [microsoft/just#63]
building using rush and pnpm results in  

```
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at webpackTask (C:\ossiaco\etorrent\common\temp\node_modules\.registry.npmjs.org\just-scripts\0.12.1\node_modules\just-scripts\lib\tasks\webpackTask.js:20:16)
    at Object.<anonymous> (C:\ossiaco\etorrent\scripts\tasks\webpack.js:8:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by kenotron** [comment]
do you have a mini-repo for me to look at? 
webpack is a devDep that is expected to have been provided by one of the just-stack-* devdeps (or your own). just-scripts doesn't include this by design.

**Comment by fuocor** [comment]
[etorrent.zip](https://github.com/microsoft/just/files/3213852/etorrent.zip)

Just unzip it and run ```npm install``` then ```npm run build```
